COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:openflowj-sdwn',
    '//protocols/openflow/api:onos-protocols-openflow-api',
    '//drivers/default:onos-drivers-default',
]

TEST_DEPS = [
    '//lib:TEST_ADAPTERS',
    '//core/api:onos-api-tests',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS,
    resources_root = 'src/main/resources',
    resources = glob(['src/main/resources/**']),
)

onos_app (
    app_name = 'org.onosproject.drivers.sdwn-drivers',
    title = 'Wireless Device Drivers',
    category = 'Drivers',
    url = 'http://inet.tu-berlin.de',
    description = 'ONOS wireless Device Drivers application.',
    included_bundles = [ ':onos-drivers-sdwn' ],
    required_apps = [ 'org.onosproject.drivers' ],
)

